### ISSUE TITLE
A1, A2, A3 Responsiveness

### ISSUE THREAD

**Issue by ccpandhare** [rishabhx64/frontend-101#1]
Welcome! 😊
--

Hi Rishabh 
Good to see that you've started with your assignment! 
I'd like to point out that your implementations of A1, A2, A3 aren't responsive enough for small width devices. The following is a screenshot of A2 on mobile (on desktop mode)
![screenshot_20171218-121134](https://user-images.githubusercontent.com/20787612/34093130-a68d510c-e3ec-11e7-94f2-24a37ea19ab5.jpg)

Use your browser's responsive mode to debug this and you'd be good to go! :-)

Also some of your grids don't align perfectly:

![screenshot_20171218-121401](https://user-images.githubusercontent.com/20787612/34093198-fa9ff100-e3ec-11e7-8cc6-627035239eb9.jpg)

Animations on A3 are good! 👍 🎉

**Comment by ccpandhare** [comment]
Also, once you're done with these bugfixes, please update [your projects page](https://github.com/rishabhx64/frontend-101/projects/1) by dragging respective cards from "to do" to "done". 

Thanks!

**Comment by rishabhx64** [comment]
Thanks for pointing out the bugs chinmay bhaiya
i have fixed the bugs with grid spacing
A2 seems to working fine now 
screenshots attached
![screenshot from 2017-12-18 21-58-19](https://user-images.githubusercontent.com/29100774/34116459-b5eb9800-e43e-11e7-8e86-2694c516ef83.png)
![screenshot from 2017-12-18 21-58-29](https://user-images.githubusercontent.com/29100774/34116462-b6718df2-e43e-11e7-8e8e-479bc39c7bac.png)

**Comment by ccpandhare** [comment]
Yes!
--
Looks much better now 🎉 
Good work; please go ahead with the other sub parts!
please move "A1", "A2", "A3" from "TO DO" to "DONE" on https://github.com/rishabhx64/frontend-101/projects/1

**Comment by ccpandhare** [comment]
Close this issue once you're done!
